version: '3'

services:
  minha-aplicacao:
    image: label/image:qa 
    ports:
      - "80:5000"
    volumes:
      - ./log:/app/log  # Mapeia a pasta de logs do container para ./logs na máquina local
